# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ECE385labsandreports/project_6final/project_6final.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5.xci
# IP: The module: 'mb_block_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE385labsandreports/project_6final/project_6final.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE385labsandreports/project_6final/project_6final.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE385labsandreports/project_6final/project_6final.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/ECE385labsandreports/project_6final/project_6final.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5.xci
# IP: The module: 'mb_block_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE385labsandreports/project_6final/project_6final.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE385labsandreports/project_6final/project_6final.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE385labsandreports/project_6final/project_6final.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
