
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_ACCUMGPIO_DEVICE_ID,
		XPAR_ACCUMGPIO_BASEADDR,
		XPAR_ACCUMGPIO_INTERRUPT_PRESENT,
		XPAR_ACCUMGPIO_IS_DUAL
	},
	{
		XPAR_LEDGPIO_DEVICE_ID,
		XPAR_LEDGPIO_BASEADDR,
		XPAR_LEDGPIO_INTERRUPT_PRESENT,
		XPAR_LEDGPIO_IS_DUAL
	},
	{
		XPAR_SWGPIO_DEVICE_ID,
		XPAR_SWGPIO_BASEADDR,
		XPAR_SWGPIO_INTERRUPT_PRESENT,
		XPAR_SWGPIO_IS_DUAL
	}
};


