# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/datafiles/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_usb/mb_usb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb || ORIG_REF_NAME==mb_usb} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_0/mb_usb_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_0 || ORIG_REF_NAME==mb_usb_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_v10_0/mb_usb_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_v10_0 || ORIG_REF_NAME==mb_usb_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_v10_0/mb_usb_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_v10_0 || ORIG_REF_NAME==mb_usb_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_0/mb_usb_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_usb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_0/mb_usb_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_usb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_lmb_bram_0 || ORIG_REF_NAME==mb_usb_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_xbar_0 || ORIG_REF_NAME==mb_usb_xbar_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_periph_0/mb_usb_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_mdm_1_0/mb_usb_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_mdm_1_0 || ORIG_REF_NAME==mb_usb_mdm_1_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_clk_wiz_1_0 || ORIG_REF_NAME==mb_usb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_usb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_uartlite_0_0 || ORIG_REF_NAME==mb_usb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/mb_usb_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_usb_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/385/lab67redo/lab67redo.gen/sources_1/bd/mb_usb/mb_usb_ooc.xdc
